# Generated by Django 5.0.6 on 2024-06-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_alter_tags_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
