# Generated by Django 5.0.6 on 2024-06-21 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0007_alter_comment_options_alter_item_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
