# Generated by Django 5.0.6 on 2024-06-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0008_item_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="replied_on",
        ),
        migrations.RemoveField(
            model_name="item",
            name="likes",
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=100, verbose_name="IP-адрес")),
                (
                    "pos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="item.item",
                        verbose_name="Новость",
                    ),
                ),
            ],
        ),
    ]
