# Generated by Django 5.0.6 on 2024-06-26 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0011_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
