# Generated by Django 5.0.6 on 2024-06-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0013_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Жалоба", "verbose_name_plural": "Жалобы"},
        ),
        migrations.AddField(
            model_name="feedback",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
