# Generated by Django 5.0.6 on 2024-06-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0015_alter_feedback_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="text",
        ),
        migrations.AddField(
            model_name="feedback",
            name="text_feedback",
            field=models.TextField(default="Жалоба"),
        ),
    ]
