# Generated by Django 5.0.6 on 2024-06-28 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0017_alter_item_options_remove_feedback_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addition",
            options={
                "verbose_name": "Дополнительная информация к посту",
                "verbose_name_plural": "Дополнительная информация к посту",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Новости", "verbose_name_plural": "Новости"},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Теги", "verbose_name_plural": "Теги"},
        ),
    ]
