# Generated by Django 4.2.3 on 2024-07-06 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_alter_item_created_at_alter_item_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 10, 43, 57, 354904)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 10, 43, 57, 354940)),
        ),
    ]
