# Generated by Django 5.0.6 on 2024-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0025_alter_item_created_at_alter_item_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
