# Generated by Django 4.2.3 on 2024-06-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0004_markedrecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription_profiles',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subscription_profiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_page.profile'),
        ),
    ]
