# Generated by Django 4.2.3 on 2024-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0005_remove_subscriptions_subscription_profiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription_profiles',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subscription_profiles',
            field=models.ManyToManyField(to='user_page.profile'),
        ),
    ]
